[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Playground"
authors = [{name = "Graziella", email = "tobias.sarosi@gmail.com"}]
dynamic = ["version", "description"]
